### ISSUE TITLE
java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Nautilus-Cloud#27]
relates to #23 

While running tests we can experience `OutOfMemoryError: Metaspace`. It looks that we have some memory leak because Metaspace usage seems to grow incessantly on each test run inside of sbt console. When you're running them with `sbt test` it's ok because a JVM is shut down after the job is done so it works now but it will stop working when we'll have more tests. 

Possible actions:
* check why it happens and try to fix it (maybe it's an actor system which is not being shut down),
* if it's because of `embedded-postgres`, we should consider replacing it with https://www.testcontainers.org/modules/databases/postgres/ which is a nice thing to do anyway because `embedded-postgres` is not maintained anymore,
* we can increase a memory for metaspace which is a temporary solution

**Comment by bhaskarkishore** [comment]
Have not encountered this in a while, closing for now. Will reopen if required.
