### ISSUE TITLE
Collect and record high level statistics from the metering systems

### ISSUE THREAD

**Issue by bhaskarkishore** [Cryptonomic/Nautilus-Cloud#73]
We would like to record high level usage statistics within the Nautilus Cloud database for non real time uses such as billing etc. This data should be stored in a separate table.

A proposed schema for this table is:
- id (int or varchar PK)
- user id  (int or varchar FK)
- service (varchar e.g Tezos, Conseil etc)
- hits (long) 
- period_start (timestamp, UTC)
- period_end (timestamp, UTC)

The above schema may be enhanced as required.

A proposed algorithm for collecting this data is as follows:

Given: 
- Time period `A`, the time interval after which the algorithm runs.
- Time period `B`, the time interval within which we are attempting to gather statistics.

Then:
1. Every `A` wake up and gather data.
1. For each user in the system, query the last recorded interval (`period_start`, `period_end`). 
1. For all metering api's listed in config, fetch all data for all api keys valid within the given periods, a) `period_start` to `period_end` and b) `period_end + B`.
1. Aggregate the two data sets collected from the previous step. Update and insert into the database respectively.

A few notes : 
1. The time periods `A` and `B` may not necessarily align i.e its possible A >> B. 
1. While the above scheme should ensure that in case of an extended outage of the NC server, It is important that any code ensure that stats are either not lost or double counted.
1. The process of collecting statistics should be kicked off immediately upon successful server start. 
1. Any failure should be recorded to log.

**Comment by piotrkosecki** [comment]
I've got few questions regarding the requirements.
1. Do we want to integrate nautilus cloud with the influxDB to do those queries? Currently metering API does not give us possibility of querying in the specific time intervals. Or do we just query for all data and for the given keys and take only those meaningful for us?(assuming those intervals will match what we have already exposed) 
2. Currently metering API exposes data for the 5m and 24h intervals - will it be enough? How we determine `A` and `B`? Should those be set in the config?

**Comment by bhaskarkishore** [comment]
>     1. Do we want to integrate nautilus cloud with the influxDB to do those queries? Currently metering API does not give us possibility of querying in the specific time intervals. Or do we just query for all data and for the given keys and take only those meaningful for us?(assuming those intervals will match what we have already exposed)

No, all queries should go through the metering api. Please feel free to enhance the endpoints in that API as required to make querying data for recording aggregates efficient and sane.

>     2. Currently metering API exposes data for the 5m and 24h intervals - will it be enough? How we determine `A` and `B`? Should those be set in the config?

The API may not be sufficient as is, but can be enhanced if required. We can set `A` and `B` to some reasonable initial values, we can start with A=B=5 minutes for starters and tune from there. These should be configurable.
